/*
 * TelaPF2.java
 *
 * Created on 25 de Novembro de 2007, 11:32
 */

package sentimentanalysis.application;


import java.awt.event.ActionListener;

/**
 *
 * @author  thuener
 */
public class TelaPF extends javax.swing.JFrame {
    
    public TelaPF(Object handle) {
        this.handle = (ActionListener) handle; 
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jCheckBoxDeletar = new javax.swing.JCheckBox();
        jCheckBoxInternet = new javax.swing.JCheckBox();
        jLabelLogin2 = new javax.swing.JLabel();
        jLabelLogin1 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldId.setColumns(20);

        jLabelLogin.setText("Identificação:");

        jCheckBoxDeletar.setSelected(true);
        jCheckBoxDeletar.setText("Deletar arquivos temporários");

        jCheckBoxInternet.setSelected(true);
        jCheckBoxInternet.setText("Tem acesso ao cineplayers");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBoxInternet)
                    .add(jCheckBoxDeletar)
                    .add(jTextFieldId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelLogin))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelLogin)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxDeletar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jCheckBoxInternet)
                .addContainerGap())
        );

        jLabelLogin2.setText("da crítica do site www.cineplayers.com");

        jLabelLogin1.setText("Insira o número de identificação");

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(handle);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(handle);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelLogin2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .add(jLabelLogin1)
                    .add(layout.createSequentialGroup()
                        .add(jButtonOk)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 102, Short.MAX_VALUE)
                        .add(jButtonSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelLogin1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelLogin2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOk)
                    .add(jButtonSair))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>
    
    private ActionListener handle;
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JCheckBox jCheckBoxDeletar;
    private javax.swing.JCheckBox jCheckBoxInternet;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLogin1;
    private javax.swing.JLabel jLabelLogin2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration
    public String getJTextFieldLogin() {
    	return jTextFieldId.getText();
	}

    public void setJCheckBoxInternet(boolean bol) {
        this.jCheckBoxInternet.setSelected(bol);
    }
    public boolean getJCheckBoxInternet() {
        return jCheckBoxInternet.isSelected();
    }
        
	public boolean getJCheckBoxDeletar() {
		return jCheckBoxDeletar.isSelected();
	}

	public void setJCheckBoxDeletar(boolean bol) {
		jCheckBoxDeletar.setSelected(bol);
	}

	public void setJTextFieldLogin(int id) {
		jTextFieldId.setText(id + "");
	}
}
